[package]
name = "rusterizer"
version = "0.1.0"
edition = "2021"
authors = ["Paul Bryden"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
