name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Change_dir
      run: cd examples/web
    - name: Build
      run: wasm-pack build --target web --out-name req_anim_frame.wasm -- --features web --no-default-features
    - name: make_deploy_dir
      run: mkdir deploy    
    - name: copy_index_html
      run: cp src/index.html deploy/.
    - name: copy_js
      run: cp pkg/req_anim_frame.wasm deploy/req_anim_frame.wasm_bg.wasm
    - name: copy_wasm_module
      run: cp pkg/req_anim_frame.js deploy/.
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v3
    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./deploy
        destination: ./_site
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
